set(CPACK_PACKAGE_NAME "xtw5-linux")
set(CPACK_PACKAGE_VENDOR "XTW Studio contributors")
set(CPACK_PACKAGE_CONTACT "https://github.com/Gm-aaa/xtw5-linux/issues")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Native Qt 6 XTW-5 USB flash programmer")
set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})
set(XTW_PACKAGE_PLATFORM "linux" CACHE STRING "Distribution identifier for release filenames")
set(CPACK_PACKAGE_FILE_NAME "xtw5-linux-${PROJECT_VERSION}-${XTW_PACKAGE_PLATFORM}-${CMAKE_SYSTEM_PROCESSOR}")
set(CPACK_PACKAGING_INSTALL_PREFIX "/usr")
set(CPACK_GENERATOR "TGZ")
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
set(CPACK_DEBIAN_PACKAGE_DEPENDS "qt6-qpa-plugins")
set(CPACK_DEBIAN_PACKAGE_RECOMMENDS "qt6-wayland, fonts-noto-cjk")
set(CPACK_DEBIAN_PACKAGE_SECTION "electronics")
set(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA "${CMAKE_SOURCE_DIR}/packaging/postinst")
set(CPACK_RPM_PACKAGE_LICENSE "LicenseRef-All-Rights-Reserved")
set(CPACK_RPM_PACKAGE_GROUP "Applications/Engineering")
set(CPACK_RPM_POST_INSTALL_SCRIPT_FILE "${CMAKE_SOURCE_DIR}/packaging/postinst")
set(CPACK_RPM_EXCLUDE_FROM_AUTO_FILELIST_ADDITION "/usr/lib/udev" "/usr/lib/udev/rules.d")
include(CPack)
